[package]
name = "curvy-utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
curvy = { path = "../program", features = ["no-entrypoint"] }
texture-common = { workspace = true }
